### ISSUE TITLE
Why the submodule PTSD include the wrong version

### ISSUE THREAD

**Issue by onon1101** [NTUT-FUCK-PTSD/Fuck-PTSD#10]
That version is not exist our config. e.g. window size...

**Comment by HeavenManySugar** [comment]
Please update submodule-ized to commit [c7dade5](https://github.com/NTUT-FUCK-PTSD/practical-tools-for-simple-design/commit/c7dade50b8299fc2e1f3133b49a0ab6c71f1b6c5)
