### ISSUE TITLE
Is it possible to make a nonlinear animation that character move in PTSD

### ISSUE THREAD

**Issue by onon1101** [NTUT-FUCK-PTSD/Fuck-PTSD#17]
when press Key W,S,D,A, the character is moving straightly. But that's not what I want.  I want that animation like this...

https://github.com/NTUT-FUCK-PTSD/Fuck-PTSD/assets/98307453/286c131b-6d63-46bc-b307-7a7b5a0456c1

**Comment by HeavenManySugar** [comment]
it's Probably fine.
It depends on the complexity of the non-linear animation.
