### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by onon1101** [NTUT-FUCK-PTSD/Fuck-PTSD#65]
Our game have a big problem that occur the memory leak in linux of raspberry 5
![image](https://github.com/NTUT-FUCK-PTSD/Fuck-PTSD/assets/98307453/994b3869-1cf9-4a9a-b179-6a535cf6b304)

**Comment by HeavenManySugar** [comment]
Missing audio device(soloud can not be initial)
