### ISSUE TITLE
Is the Type `const char *` not allow to transfer to function `LOG_INFO` ?

### ISSUE THREAD

**Issue by onon1101** [NTUT-FUCK-PTSD/Fuck-PTSD#67]

**Comment by HeavenManySugar** [comment]
I don't know but you can check this
![image](https://github.com/NTUT-FUCK-PTSD/Fuck-PTSD/assets/25154413/f3e28dc3-11b9-4bc0-836b-2d1aabdd9491)
![image](https://github.com/NTUT-FUCK-PTSD/Fuck-PTSD/assets/25154413/b98e4131-d858-491f-aff0-53e6a7ada101)

**Comment by HeavenManySugar** [comment]
I think we should use const string instead of const char*
